### ISSUE TITLE
Markers stream not working

### ISSUE THREAD

**Issue by bornold** [qualisys/Qualisys-Unity-SDK#1]
Markers positions gets wrong label when changing the markers order in QTM.

Reproducing steps:
1. Start streaming with a file from QTM to Unity.
2. Change place of two markers in QTM. (Move marker up or down in Labeled trajectories)
3. Wait for the stream to restart from the beginning.
4. The two markers now have each others positions.

![image](https://cloud.githubusercontent.com/assets/2464109/8933702/83537f30-3544-11e5-8ab4-be16e4e2a364.png)
In picture, R_SAE and L_HM2 has changed position.

**Comment by qualisys** [comment]
This is an Realtime server issue with QTM which is made visible by streaming markers and bones to Unity. The issue has been added to the QTM list and will be fixed.
