### ISSUE TITLE
Is it possible to run files unity without QTM

### ISSUE THREAD

**Issue by jeffsee55** [qualisys/Qualisys-Unity-SDK#14]
I'm new to this and am jumping in from the Unity side, I see that QTM software is necessary for real-time streaming to Unity, however I'm wondering if it's possible to just use the QTM exported files without the software.

**Comment by mlveggo** [comment]
Hi,

If the animations are exported as FBX files then they can be imported directly into Unity.

Here is a video showing how to import fbx data into Unity.
https://www.youtube.com/watch?v=45lpApQexoM

Here is another with streaming from QTM
https://www.youtube.com/watch?v=QOW7fFjhviY

Best regards,
Morgan
