### ISSUE TITLE
Build Errors when building for the Universal Windows Platform in Unity

### ISSUE THREAD

**Issue by trueivorian** [qualisys/Qualisys-Unity-SDK#15]
![image](https://user-images.githubusercontent.com/15149274/75251527-ac149480-57d2-11ea-8e26-1b9947fdd3ab.png)

The RT Client works fine in the editor however these errors are preventing a successful build. This was run on Unity 2018.4.17f1 for a Hololens application on the Universal Windows Platform.

**Comment by mbaytas** [comment]
Some time ago, we have spent quite a lot of time hacking on the HoloLens 1. Unfortunately networking on that device was a challenge. Basically the HoloLens 1 hardware and Unity use different namespaces for networking-related functions. Specifically, Unity uses the System.Net namespace, while the HoloLens uses Windows.Networking.

 This was an infamous pain point among HoloLens developers. The conclusion is that any networking code that works in the Unity Editor and Emulator will not work on the HoloLens device, and vice versa. Thus, you need to use statements like `#if !UNITY_EDITOR` to have code that runs selectively, based on where it is running. As you might imagine, this makes debugging very challenging.

In one particular case, we were able to establish a UDP connection using the following Unity project and C# app:

- https://github.com/mbaytas/HoloLensUDP - Unity prefabs etc. (includes links to resources about the networking issue at large)
- https://github.com/mbaytas/QualisysUDP - Little Windows app for streaming from QTM

Unfortunately the HoloLens side of it was not super stable. We even had experiences where changing comments or spaces in the code would break functionality!

It might be the case that these issues are addressed in HoloLens 2, which we have not yet tested. About a year ago, we tried the Magic Leap headset, and we did not have any issues. We have a complete example Unity project for that device: https://github.com/mbaytas/QTM-MagicLeap

**Comment by trueivorian** [comment]
Thanks for the reply! I didn't find a solution in the end with HoloLens 1, but will consider Magic Leap implementations in future!
